### ISSUE TITLE
[FEAT] Question Feed

### ISSUE THREAD

**Issue by marchfirst01** [Codeit-Sprint/OpenMind#25]
## 📌 Feature 이슈

Question Feed

## ✏️ To-do

- [x] 질문이 없는 경우 화면 구성
- [x] 질문 있을 경우 안쪽에 컴포넌트 삽입
- [x] 기기별 반응형 화면 구성

## 📸 스크린샷(선택)

<img width="470" alt="image" src="https://github.com/Codeit-Sprint/OpenMind/assets/140829640/d93be485-edd6-4510-90fc-aa48d0428bb7">
<img width="579" alt="image" src="https://github.com/Codeit-Sprint/OpenMind/assets/140829640/340dddb9-98d3-4c22-af98-802a7b0d74e3">
